### ISSUE TITLE
warning: possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by cadorn** [persvr/jsgi-node#3]
I just upgraded from `node` **0.2.6** to **0.4.2** and am now getting the following error:

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace: 
    at Socket.<anonymous> (events.js:101:17)
    at handle (/Users/cadorn/pinf/workspaces/github.com/pinf/loader-js/demos/ACE/.pinf-packages/downloads/github.com/kriszyp/jsgi-node/zipball/v0.2.3~sources/lib/jsgi-node.js:135:16)
    at Array.0 (/Users/cadorn/pinf/workspaces/github.com/pinf/loader-js/demos/ACE/.pinf-packages/downloads/github.com/kriszyp/jsgi-node/zipball/v0.2.3~sources/lib/jsgi-node.js:221:7)
    at EventEmitter._tickCallback (node.js:108:26)
```

I presume this is a bug in _jsgi-node_?

**Comment by cadorn** [comment]
Looks like a duplicate of this issue:

https://github.com/kriszyp/jsgi-node/issues/unreads#issue/2

**Comment by kriszyp** [comment]
Is this still an issue after the commits from https://github.com/kriszyp/jsgi-node/pull/2?

**Comment by cadorn** [comment]
nope. saw that on the master after filing this issue.

It's all good now. We just need a new release tagged.

**Comment by kriszyp** [comment]
Ok, tagged the latest
